# Generated by Django 2.0.3 on 2018-03-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0006_auto_20180323_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='date',
        ),
        migrations.RemoveField(
            model_name='image',
            name='time',
        ),
        migrations.AddField(
            model_name='image',
            name='datetime_published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
