# Generated by Django 2.0.3 on 2018-03-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0007_auto_20180323_2113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.AddField(
            model_name='image',
            name='neuro_result',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
