# Generated by Django 2.0.3 on 2018-03-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0008_auto_20180327_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='path_toResult',
            field=models.CharField(default='None', max_length=256),
        ),
    ]
